### ISSUE TITLE
Project Adoption

### ISSUE THREAD

**Issue by brandonroberts** [brandonroberts/ngrx-store-freeze#18]
@tsm91, @cyrip 

I am one of the maintainers of the NgRx project This [issue](https://github.com/ngrx/platform/issues/393) lays out that we plan on adding "freeze" functionality to `Store` in the future. In the meantime, I would like to take ownership of this project for the foreseeable future. 

If you are willing to transfer the project, you can email me using my github email or reply here.

**Comment by tsm91** [comment]
Hey @brandonroberts, thank you for your effort. As i mentioned in https://github.com/codewareio/ngrx-store-freeze/issues/17#issuecomment-329259793, im looking for a maintainer. I'd happily transfer ownership of the repo and give [publish access on npm](https://docs.npmjs.com/cli/owner).

It's been a while since i touched the NgRx ecosystem and Angular. I feel bad about the piling issues.

In the following minutes / hour I'll make the necessary steps.

**Comment by brandonroberts** [comment]
@tsm91 I got the repo ownership transferred. Can you give me access on npm?

**Comment by tsm91** [comment]
@brandonroberts i believe i did. However this is the first time i gave publish access on npm, maybe i messed something up.

I executed the following: `npm owner add brandonroberts ngrx-store-freeze` After i executed `npm owner ls ngrx-store-freeze` and your credentials were listed in the stdout.

If you check https://www.npmjs.com/~brandonroberts, ngrx-store-freeze is in the list of packages. Also if you check https://www.npmjs.com/package/ngrx-store-freeze you are in the collabolators list.

**Comment by brandonroberts** [comment]
Ok cool. I didn't see it when I looked before. Thanks!
